[telegram]
bot_token = "YOUR_TELEGRAM_BOT_TOKEN"
chat_id = 123456789

[sites]
urls = [
    "https://example.com",
    "https://google.com",
]

[settings]
check_interval = 300     # Интервал проверки (в секундах)
timeout = 10             # Таймаут запроса (в секундах)